DROP TABLE IF EXISTS authors;
CREATE TABLE authors(id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), surname VARCHAR(255), PRIMARY KEY (id));
DROP TABLE IF EXISTS genres;
CREATE TABLE genres(id INT NOT NULL AUTO_INCREMENT, genre_name VARCHAR(255), PRIMARY KEY (id));
DROP TABLE IF EXISTS books;
CREATE TABLE books (id INT NOT NULL AUTO_INCREMENT, title VARCHAR(255), author_id INT, genre_id INT, PRIMARY KEY (id), CONSTRAINT FK_BOOKS_AUTHORS FOREIGN KEY (author_id) REFERENCES authors(id), CONSTRAINT FK_BOOKS_GENRES FOREIGN KEY (genre_id) REFERENCES genres(id));